name: fry-gbp
version: "${pluginVersion}"
description: Permissions plugin focussed around easy administering of group memberships
author: frymaster@127001.org
website: http://frymaster.127001.org
main: org._127001.frymaster.gbp.Gbp
commands:
  gbp:
    description: Manage permissions
    usage: /<command> help for command overview
    permission: gbp.manage
permissions:
  gbp:
    description: Manage permissions
    default: op   